//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _122_Rogosin_UP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int ID { get; set; }
        public int user_login_id { get; set; }
        public int user_password_id { get; set; }
        public int ad_title { get; set; }
        public int ad_description { get; set; }
        public int ad_post_date { get; set; }
        public int city_id { get; set; }
        public int category_id { get; set; }
        public int ad_type_id { get; set; }
        public int ad_status_id { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual Ad_Description Ad_Description1 { get; set; }
        public virtual Ad_post_date Ad_post_date1 { get; set; }
        public virtual Ad_Status Ad_Status { get; set; }
        public virtual Ad_Title Ad_Title1 { get; set; }
        public virtual Ad_Type Ad_Type { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Users_Login Users_Login { get; set; }
        public virtual Users_Password Users_Password { get; set; }
    }
}
