//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _122_Rogosin_UP02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad_Title
    {
        public Ad_Title()
        {
            this.Ad = new HashSet<Ad>();
        }
    
        public string ad_title1 { get; set; }
        public int ID { get; set; }
    
        public virtual ICollection<Ad> Ad { get; set; }
    }
}
