//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _122_Rogosin_UP02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ad> Ad { get; set; }
        public DbSet<Ad_Description> Ad_Description { get; set; }
        public DbSet<Ad_post_date> Ad_post_date { get; set; }
        public DbSet<Ad_Status> Ad_Status { get; set; }
        public DbSet<Ad_Title> Ad_Title { get; set; }
        public DbSet<Ad_Type> Ad_Type { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users_Login> Users_Login { get; set; }
        public DbSet<Users_Password> Users_Password { get; set; }
    }
}
